version: '4'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: node
    restart: always
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file: .env
    ports:
      - "27017:${MONGO_PORT}"
    volumes:
      - ./db:/data/db